theme: jekyll-theme-minimal
#Google Analytics
google_analytics: G-2NEE9XL52D  # your google analytics
title: Zhengyu Hu

logo: img/Img4.jpg
email: huzhengyu477@gmail.com
scholar_url: https://scholar.google.com/citations?user=_WJtdlcAAAAJ
twitter_url: https://x.com/ZhengyuHu477
# github_url: https://github.com/ppsmk388
